## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: workshopmesh
  properties:
    services:
      - name: WorkshopMeshFrontend
        properties:
          description: WorkshopMeshFrontend description.
          osType: Windows
          codePackages:
            - name: WorkshopMeshFrontend
              image: workshopmeshfrontend:dev
              volumes:
                - name: "sfvol"
                  creationParameters:
                  kind: ServiceFabricVolumeDisk
                  sizeDisk: Small
                  destinationPath: C:/data/
              endpoints:
                - name: WorkshopMeshFrontendListener
                  port: 80
#              environmentVariables:
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: "[parameters('WorkshopMeshFrontend_cpu')]"
                  memoryInGB: 1
          replicaCount: 2
          networkRefs:
            - name: workshopmeshNetwork
              endpointRefs:
                - name: WorkshopMeshFrontendListener
